---
kind: pipeline
name: default
steps:
- name: get Cachet file
  image: isaackuang/tools
  commands:
   - wget https://github.com/CachetHQ/Cachet/archive/2.4.tar.gz
   - tar zxvf 2.4.tar.gz
- name: composer install
  image: isaackuang/php-composer
  commands:
  - cd Cachet-2.4
  - composer install --no-dev
- name: build Docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: isaackuang/cachet
    tags: latest